server:
  port: ${port:8080}

api:
  version:
    default: 1.0

swagger:
  enable: true

jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 60000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password:
    hikari:
      connectionTimeout: 30000  # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10          # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10     # maximum pool size
      max-lifetime: 1800000     # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true         # default auto-commit behavior.
      idle-timeout: 600000      # maximum idle time for connection
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop     # Hibernate ddl auto (none, validate, update, create, create-drop) - CREATE DATABASE databasename CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    open-in-view: true          # As OSIV affects the connection and performance of the database, this warning log will be displayed when starting the spring boot application.